# Generated by Django 4.2.7 on 2023-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.FileField(upload_to='uploads/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
