# Generated by Django 4.2.7 on 2024-01-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='job',
        ),
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.AlterField(
            model_name='content',
            name='attached',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
