# Generated by Django 4.2.7 on 2024-01-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='stack',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
