# Generated by Django 4.2.7 on 2023-11-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_content_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comment_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.content')),
            ],
        ),
    ]
