# Generated by Django 4.2.7 on 2024-01-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_content_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.content'),
        ),
    ]
