# Generated by Django 4.2.7 on 2024-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0003_alter_comment_content_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='like_users',
            field=models.ManyToManyField(related_name='like_contents', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='scrap_users',
            field=models.ManyToManyField(related_name='scrap_contents', to='accounts.userprofile'),
        ),
    ]
