# Generated by Django 4.2.7 on 2023-11-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_content_comment_cnt_content_like_cnt_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='scrap_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
