# Generated by Django 4.2.7 on 2024-01-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_user_id'),
        ('home', '0003_alter_content_job_alter_content_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='content',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_contents', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='content',
            name='scrap_users',
            field=models.ManyToManyField(null=True, related_name='scrap_contents', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
