# Generated by Django 4.2.7 on 2023-11-27 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_content_scrap_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.content'),
        ),
    ]
