# Generated by Django 4.2.7 on 2024-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0004_alter_content_like_users_alter_content_scrap_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_contents', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='scrap_users',
            field=models.ManyToManyField(blank=True, related_name='scrap_contents', to='accounts.userprofile'),
        ),
    ]
