# Generated by Django 4.2.7 on 2024-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('student_num', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('job', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stack', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
