# Generated by Django 4.2.7 on 2023-12-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social',
        ),
        migrations.DeleteModel(
            name='GoogleLogin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
