# Generated by Django 4.2.7 on 2024-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(max_length=150, unique=True),
        ),
    ]
